package:
  name: git-shim
  version: 1.5.0
  epoch: 0
  description: This git shim replaces any URL or SCP-style URL as an argument to git with an HTTPS URL.
  target-architecture:
    - x86_64
    - aarch64
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - ca-certificates-bundle
      - git
      - git-lfs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
      - https://packages.cgr.dev/extras/chainguard-extras.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
      - https://packages.cgr.dev/extras
    packages:
      - busybox
      - ca-certificates-bundle
      - git
      - go

vars:
  gem: parallel

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/dependabot/${{package.name}}
      tag: v${{package.version}}
      expected-commit: af162fe63aacfba741d8cf058384c9af52b82e44

  - uses: go/build
    with:
      packages: .
      prefix: /home/dependabot/dependabot-updater
      output: git

  - uses: strip
