archs:
  - x86_64
  - aarch64

contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - apko
    - aws-cli
    - bash
    - busybox
    - ca-certificates
    - ca-certificates-bundle
    - curl
    - docker-cli
    - gettext
    - git
    - melange
    - openssl
    - regclient
    - unzip
    - vault
    - wget
    - wolfi-base

annotations:
  image-author: 'GitGuardian SRE Team <sre@gitguardian.com>'

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: nonroot

work-dir: /home/nonroot
